server:
  port: ${CUSTOMER_PORT:8080}

logging:
  level:
    br.com.erpsystem: DEBUG

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  application:
    name: ms-customer
#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    port: ${RABBITMQ_PORT:5672}
#    listener:
#      simple:
#        max-concurrency: 2
#    connection-timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST/db_01_customer_ms:jdbc:mysql://localhost:3306/db_01_customer_ms}
    username: ${MYSQL_USERNAME:customer-user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



