spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST:jdbc:mysql://localhost:3306/db_01_customer_ms}
    username: ${MYSQL_USERNAME:customer-user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



